version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/auth"
    update_schedule: "daily"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "security:patch"
      - match:
          dependency_type: "all"
          update_type: "semver:patch"
      - match:
          dependency_type: "all"
          update_type: "semver:minor"

